// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrea Benetton
//! The human client's reference views (plan §17 (8)): Slint components
//! bound to `ui-model`, agreed with rust-ui-dev before they were built
//! (relay seqs 10823, 10826, 10849; the input queue 10867, 10870, 10879,
//! 10882, 10885).
//!
//! A view reads a [`UiModel`] and nothing else, and a person's actions
//! leave it as [`ViewEvent`]s -- it never calls the facade, the store or
//! IPC. A Slint callback cannot see the model, so it decides nothing: it
//! queues what the person pressed, by identity, and [`View::take_events`]
//! resolves each press against the model it is handed then.
//!
//! The crate names the toolkit and no windowing backend or renderer:
//! which ones ship is the apps' decision at Stage 15.

// No `forbid(unsafe_code)` here, unlike the other human crates: the
// code slint-build generates allows `unsafe_code` locally, which a
// crate-level `forbid` refuses. The workspace's `deny` still holds every
// handwritten line in this crate.

use std::cell::RefCell;
use std::collections::{BTreeMap, HashMap, VecDeque};
use std::rc::Rc;

use interweave_human_ui_model::{
    ConversationKey, Direction, Intent, ItemKey, ItemStatus, MessageItem, Reply, Retention,
    SessionNotice, UiModel, UiText, fill, placeholder_en, short_peer,
};
use slint::{Model as _, ModelRc, SharedString, VecModel};

mod body;

#[allow(
    missing_docs,
    unreachable_pub,
    rust_2018_idioms,
    clippy::all,
    clippy::pedantic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::todo,
    clippy::unimplemented,
    clippy::dbg_macro,
    reason = "generated by slint-build from ui/app.slint; the handwritten code is held to the workspace lints"
)]
mod generated {
    slint::include_modules!();
}

pub use generated::AppWindow;
use generated::{ActionRow, BodyLine, ConversationRow, LineKind, LinkRow, MessageRow};

/// The view's window, to run the event loop on: shows it, and returns
/// once the person closes it or [`quit_event_loop`] is called.
pub struct WindowHandle(AppWindow);

impl WindowHandle {
    /// Show the window and run the event loop until it is closed.
    ///
    /// # Errors
    /// The toolkit's, as text: no window could be shown.
    pub fn run(&self) -> Result<(), String> {
        slint::ComponentHandle::run(&self.0).map_err(|e| e.to_string())
    }
}

/// Run `task` on the window's thread at its next turn, from any thread:
/// how the facade's thread tells the window it has something to take.
/// False once the event loop has ended.
pub fn invoke_on_window(task: impl FnOnce() + Send + 'static) -> bool {
    slint::invoke_from_event_loop(task).is_ok()
}

/// Run `task` on the window's thread after the current event is handled,
/// never inside it: how the view's own wake hook schedules a turn without
/// re-entering one.
pub fn defer(task: impl FnOnce() + 'static) {
    slint::Timer::single_shot(std::time::Duration::ZERO, task);
}

/// End the event loop: [`WindowHandle::run`] returns.
pub fn quit_event_loop() {
    // An event loop already gone has nothing to end.
    let _ = slint::quit_event_loop();
}

/// What the platform lacks for the views to work.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlatformProblem {
    /// The fontconfig library did not load: the toolkit opens it at run
    /// time, and without it every text renders with no font at all.
    NoFontconfig,
}

/// Check, before any window, that the platform has what the views need.
/// It asks the same loader the toolkit's font stack uses, so the answer
/// is the stack's own: a host without the library would otherwise run
/// with no fonts, silently.
///
/// # Errors
/// The first [`PlatformProblem`] found.
pub fn platform_check() -> Result<(), PlatformProblem> {
    #[cfg(all(unix, not(target_vendor = "apple")))]
    if fontconfig_sys::statics::LIB_RESULT.is_err() {
        return Err(PlatformProblem::NoFontconfig);
    }
    Ok(())
}

/// How many PRESSES wait for [`View::take_events`] at most. A full queue
/// refuses the NEWEST press and counts it: a refused press does nothing
/// and can be pressed again, where dropping the oldest could drop an edit
/// and keep the send after it (agreed, relay seq 10882). Edits and focus
/// changes are state, not presses, and are never refused; with them, and
/// a root that drains the queue whenever it takes, the queue holds at most
/// four times this plus three ([`View::queued_inputs`]). A root that stops
/// between takes breaks that number, not the bound: one more edit can
/// wait per conversation selected meanwhile, so the queue stays finite.
pub const INPUT_CAP: usize = 64;

/// What a view asks of the composition root. Defined in `ui-model`, so a
/// root that names no toolkit can handle it; re-exported here because a
/// view is where it comes from.
pub use interweave_human_ui_model::ViewEvent;

/// A press, as the person made it, before the model has judged it.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Input {
    Select(ConversationKey),
    Focus(bool),
    /// An item action, by IDENTITY: the item and the intent as rendered,
    /// never a position a re-render could move (agreed P1).
    Action(ItemKey, Intent),
    /// The notice's action, with the notice that was shown.
    Notice(SessionNotice),
    /// A link's control, with the destination as rendered: the model
    /// checks its scheme again before it becomes an intent.
    Link(String),
    Send(ConversationKey),
    Draft(ConversationKey, String),
}

/// What a press on an item resolves against: the item, its actions and
/// its links as rendered.
#[derive(Clone)]
struct Pressable {
    key: ItemKey,
    actions: Vec<Intent>,
    links: Vec<String>,
}

/// What the callbacks share with the view: the queue, and what was on
/// screen when a press happened, so a press is recorded as what the
/// person saw.
///
/// THE QUEUE'S ORDER IS THE PERSON'S ORDER. No queued input is ever moved
/// relative to another, and nothing a person did is held outside it: an
/// edit or a focus change is never refused, and coalesces only in place,
/// into an entry it can replace without changing what any input between
/// them resolves to. The one thing outside the queue is a render's
/// "viewed", which the root made, resolved once the queue has drained.
/// Three review rounds on #170 found inputs moved or held aside -- a focus
/// change moved past selections, a refused edit reported out of order and
/// then lost when the conversation changed -- so the edit is now in the
/// queue by construction rather than restored to its place.
#[derive(Default)]
struct Shared {
    inputs: VecDeque<Input>,
    refused: u64,
    conversations: HashMap<i32, ConversationKey>,
    items: HashMap<i32, Pressable>,
    selected: Option<ConversationKey>,
    /// A render showed a conversation with unread items: once the queue
    /// has drained, read the conversation then shown if the window then
    /// has focus (rust-ui-dev F1). Resolved last, it can only read fewer.
    viewed: bool,
    notice: Option<SessionNotice>,
    wake: Option<Rc<dyn Fn()>>,
}

impl Shared {
    /// Queue `input`, and return the wake hook for the caller to run once
    /// it has RELEASED its borrow of this state: a hook that takes at
    /// once borrows it again (review F3).
    #[must_use]
    fn push(&mut self, input: Input) -> Option<Rc<dyn Fn()>> {
        // An edit is the composer's STATE: refusing it loses what the
        // person typed (review R2-1), so it is never refused. It replaces a
        // queued edit for the same conversation only while no later input
        // for that conversation follows it -- folding it past a send would
        // send text typed after the press (agreed, relay seq 10885) --
        // otherwise it is appended. So at most one edit waits between any
        // two presses for its conversation.
        if let Input::Draft(key, text) = &input {
            let last_for_key = self.inputs.iter_mut().rev().find(|i| match i {
                Input::Draft(k, _) | Input::Send(k) | Input::Select(k) => k == key,
                _ => false,
            });
            if let Some(Input::Draft(_, queued)) = last_for_key {
                queued.clone_from(text);
            } else {
                self.inputs.push_back(input);
            }
            return self.wake.clone();
        }
        // A focus change is STATE, not a press: refusing it would leave the
        // view believing it still had focus, and a later selection would
        // read while unfocused (review F2). So it is never refused. It
        // replaces a queued focus change only when that is the LAST input
        // -- in place, so nothing moves (rust-ui-dev R1, review N2) -- which
        // leaves at most one between any two other inputs.
        if let Input::Focus(_) = input {
            match self.inputs.back_mut() {
                Some(last @ Input::Focus(_)) => *last = input,
                _ => self.inputs.push_back(input),
            }
            return self.wake.clone();
        }
        let presses = self
            .inputs
            .iter()
            .filter(|i| !matches!(i, Input::Focus(_) | Input::Draft(..)))
            .count();
        if presses >= INPUT_CAP {
            self.refused += 1;
            return None;
        }
        self.inputs.push_back(input);
        self.wake.clone()
    }
}

/// Queue `input` from a window callback, and wake the root after the
/// borrow is released. The root's own calls queue without waking: the
/// root is in control already, and may hold the view borrowed (review N4).
fn enqueue(shared: &RefCell<Shared>, input: Input) {
    let wake = shared.borrow_mut().push(input);
    if let Some(wake) = wake {
        wake();
    }
}

/// Stable small handles for keys, so a Slint row names its key without
/// the key's own representation crossing into the toolkit.
struct Handles<K> {
    by_key: BTreeMap<K, i32>,
    next: i32,
}

impl<K: Ord + Clone> Handles<K> {
    const fn new() -> Self {
        Self {
            by_key: BTreeMap::new(),
            next: 0,
        }
    }

    fn of(&mut self, key: &K) -> i32 {
        if let Some(handle) = self.by_key.get(key) {
            return *handle;
        }
        let handle = self.next;
        self.next = self.next.wrapping_add(1);
        self.by_key.insert(key.clone(), handle);
        handle
    }

    fn retain(&mut self, live: &[K]) {
        self.by_key.retain(|k, _| live.contains(k));
    }
}

/// The reference view: one window, bound to a [`UiModel`].
pub struct View {
    window: AppWindow,
    conversations: Rc<VecModel<ConversationRow>>,
    conversation_keys: Vec<ConversationKey>,
    conversation_handles: Handles<ConversationKey>,
    messages: Rc<VecModel<MessageRow>>,
    message_keys: Vec<ItemKey>,
    item_handles: Handles<ItemKey>,
    /// Each item's actions model, kept while its actions are the same: a
    /// row compares its actions by model identity, so a fresh model on
    /// every render would rebuild the buttons and drop a focused one
    /// (review F1).
    action_models: HashMap<i32, (Vec<Intent>, ModelRc<ActionRow>)>,
    /// Each item's drawn body, kept while the item is shown: a body never
    /// changes, and a fresh model would rebuild a focused link's control,
    /// as a fresh actions model would (review F1). Keyed by the item, not
    /// its handle, which a later item may reuse.
    bodies: HashMap<ItemKey, DrawnBody>,
    shown: Option<ConversationKey>,
    focused: bool,
    shared: Rc<RefCell<Shared>>,
}

impl View {
    /// A view over a new window. Shows nothing until [`render`](Self::render).
    ///
    /// # Errors
    /// The toolkit's, when no platform can create a window.
    pub fn new() -> Result<Self, slint::PlatformError> {
        let window = AppWindow::new()?;
        let conversations = Rc::new(VecModel::<ConversationRow>::default());
        let messages = Rc::new(VecModel::<MessageRow>::default());
        window.set_conversations(ModelRc::from(Rc::clone(&conversations)));
        window.set_messages(ModelRc::from(Rc::clone(&messages)));
        let text = |t| SharedString::from(placeholder_en::text(t));
        window.set_window_title(text(UiText::AppTitle));
        window.set_conversations_heading(text(UiText::Conversations));
        window.set_messages_heading(text(UiText::Messages));
        window.set_header_id_label(text(UiText::ConversationId));
        window.set_composer_label(text(UiText::Composer));
        window.set_send_label(text(UiText::Send));
        window.set_show_source_label(text(UiText::ShowSource));
        window.set_show_formatted_label(text(UiText::ShowFormatted));
        let shared = Rc::new(RefCell::new(Shared::default()));

        let s = Rc::clone(&shared);
        window.on_select(move |handle| {
            let key = s.borrow().conversations.get(&handle).cloned();
            if let Some(key) = key {
                enqueue(&s, Input::Select(key));
            }
        });
        let s = Rc::clone(&shared);
        window.on_action(move |handle, index| {
            let pressed = s.borrow().items.get(&handle).and_then(|item| {
                usize::try_from(index)
                    .ok()
                    .and_then(|i| item.actions.get(i))
                    .map(|intent| (item.key, intent.clone()))
            });
            if let Some((key, intent)) = pressed {
                enqueue(&s, Input::Action(key, intent));
            }
        });
        let s = Rc::clone(&shared);
        window.on_link(move |handle, index| {
            let pressed = s.borrow().items.get(&handle).and_then(|item| {
                usize::try_from(index)
                    .ok()
                    .and_then(|i| item.links.get(i).cloned())
            });
            if let Some(destination) = pressed {
                enqueue(&s, Input::Link(destination));
            }
        });
        let s = Rc::clone(&shared);
        window.on_send(move || {
            let selected = s.borrow().selected.clone();
            if let Some(key) = selected {
                enqueue(&s, Input::Send(key));
            }
        });
        let s = Rc::clone(&shared);
        window.on_notice_pressed(move || {
            let notice = s.borrow().notice;
            if let Some(notice) = notice {
                enqueue(&s, Input::Notice(notice));
            }
        });
        let s = Rc::clone(&shared);
        window.on_draft_edited(move |text| {
            let selected = s.borrow().selected.clone();
            if let Some(key) = selected {
                enqueue(&s, Input::Draft(key, text.to_string()));
            }
        });

        Ok(Self {
            window,
            conversations,
            conversation_keys: Vec::new(),
            conversation_handles: Handles::new(),
            messages,
            message_keys: Vec::new(),
            item_handles: Handles::new(),
            action_models: HashMap::new(),
            bodies: HashMap::new(),
            shown: None,
            focused: false,
            shared,
        })
    }

    /// The window, to show it or to inspect its tree.
    #[must_use]
    pub const fn window(&self) -> &AppWindow {
        &self.window
    }

    /// A handle on the window that outlives a borrow of the view: the root
    /// keeps the view where its turns can reach it and runs the event
    /// loop from this.
    #[must_use]
    pub fn handle(&self) -> WindowHandle {
        WindowHandle(slint::ComponentHandle::clone_strong(&self.window))
    }

    /// Tell `focused` each time the window gains or loses the person's
    /// focus, from the windowing system itself (winit's `Focused`): what
    /// [`set_window_focused`](Self::set_window_focused) is driven from on
    /// the desktop. A read is gated on it, and until the first event the
    /// view counts as unfocused, so nothing is read before then.
    #[cfg(feature = "desktop")]
    pub fn on_window_focus(&self, focused: impl Fn(bool) + 'static) {
        use slint::winit_030::{EventResult, WinitWindowAccessor as _, winit::event::WindowEvent};
        slint::ComponentHandle::window(&self.window).on_winit_window_event(move |_, event| {
            if let WindowEvent::Focused(now) = event {
                focused(*now);
            }
            EventResult::Propagate
        });
    }

    /// Called whenever a window callback queues an input, so the root runs
    /// [`take_events`](Self::take_events) without waiting for an
    /// unrelated event. It runs with no borrow of the view's state held,
    /// so it may take at once. The root's own calls -- [`select`](Self::select),
    /// [`set_window_focused`](Self::set_window_focused), [`render`](Self::render)
    /// -- do not run it: the root then takes when it is ready.
    pub fn set_wake(&self, wake: impl Fn() + 'static) {
        self.shared.borrow_mut().wake = Some(Rc::new(wake));
    }

    /// Select a conversation, as a click on its row does.
    pub fn select(&self, key: ConversationKey) {
        let _ = self.shared.borrow_mut().push(Input::Select(key));
    }

    /// The window gained or lost the person's focus. The platform's
    /// activation signal drives it at Stage 15; here the root, or a
    /// test, does (U3b).
    pub fn set_window_focused(&self, focused: bool) {
        let _ = self.shared.borrow_mut().push(Input::Focus(focused));
    }

    /// How many inputs wait for a take. While the root drains the queue to
    /// empty whenever it takes -- the contract on
    /// [`take_events`](Self::take_events) -- never more than [`INPUT_CAP`]
    /// presses, one edit beside each press plus one, and one focus change
    /// beside every other input plus one: four times the cap plus three. A
    /// root that stops between takes can leave a selection taken and later
    /// inputs queued, which lets one more edit wait per conversation
    /// selected that way; the queue stays finite, not at that number.
    #[must_use]
    pub fn queued_inputs(&self) -> usize {
        self.shared.borrow().inputs.len()
    }

    /// How many inputs a full queue refused.
    #[must_use]
    pub fn refused_inputs(&self) -> u64 {
        self.shared.borrow().refused
    }

    /// Resolve queued inputs against `model`, oldest first, up to and
    /// including the first draft edit: the root applies that edit and
    /// calls again, so a send queued after an edit reads the edited draft
    /// (agreed P2). The root calls again until a call returns nothing,
    /// before it returns to its event loop: that is what keeps the queue
    /// at its bound ([`queued_inputs`](Self::queued_inputs)). A press
    /// whose action the model no longer offers yields nothing -- never
    /// another action (agreed P1). Once the queue
    /// has drained, a render's "viewed" is resolved against the focus and
    /// conversation of that moment.
    pub fn take_events(&mut self, model: &UiModel) -> Vec<ViewEvent> {
        let mut out = Vec::new();
        loop {
            let next = self.shared.borrow_mut().inputs.pop_front();
            let Some(input) = next else {
                break;
            };
            match input {
                Input::Select(key) => {
                    out.extend(
                        model
                            .conversation_viewed(&key, self.focused)
                            .into_iter()
                            .map(ViewEvent::Intent),
                    );
                    self.shared.borrow_mut().selected = Some(key.clone());
                    self.shown = Some(key);
                }
                Input::Focus(focused) => {
                    self.focused = focused;
                    if let Some(key) = &self.shown {
                        out.extend(
                            model
                                .conversation_viewed(key, focused)
                                .into_iter()
                                .map(ViewEvent::Intent),
                        );
                    }
                }
                Input::Action(key, intent) => {
                    if model.actions(key).contains(&intent) {
                        out.push(ViewEvent::Intent(intent));
                    }
                }
                Input::Link(destination) => {
                    out.extend(model.link_activated(&destination).map(ViewEvent::Intent));
                }
                Input::Notice(shown) => {
                    if model.session_notice() == Some(shown) {
                        out.extend(shown.resolution().map(ViewEvent::Intent));
                    }
                }
                Input::Send(key) => {
                    out.extend(model.send_draft(&key).map(ViewEvent::Intent));
                }
                Input::Draft(key, draft) => {
                    out.push(ViewEvent::DraftChanged { key, draft });
                    return out;
                }
            }
        }
        // The queue has drained: a render's "viewed" is resolved against the
        // focus and the conversation of this moment, so it can only read
        // less than the person's order would.
        let viewed = std::mem::take(&mut self.shared.borrow_mut().viewed);
        if viewed && let Some(key) = &self.shown {
            for intent in model.conversation_viewed(key, self.focused) {
                // A focus gained or a selection in this same take may have
                // read these already: one intent per row.
                let event = ViewEvent::Intent(intent);
                if !out.contains(&event) {
                    out.push(event);
                }
            }
        }
        out
    }

    /// Show `model`. Lists are updated BY KEY -- a row's data replaced in
    /// place, rows inserted and removed where they changed -- never by
    /// replacing a whole model, which would move keyboard focus and a
    /// screen reader's place back to the start (U3a).
    ///
    /// A shown conversation holding unread items marks the view "viewed",
    /// so a message that arrives while the person reads it is marked read
    /// at the end of the next take if the window has focus then. It does
    /// not wake the root, which is rendering: the root takes after it
    /// renders.
    pub fn render(&mut self, model: &UiModel) {
        self.render_conversations(model);
        self.render_messages(model);
        self.render_chrome(model);
        if let Some(key) = &self.shown {
            let unread = model
                .conversations()
                .iter()
                .any(|s| &s.key == key && s.unread > 0);
            if unread {
                self.shared.borrow_mut().viewed = true;
            }
        }
    }

    fn render_conversations(&mut self, model: &UiModel) {
        let summaries = model.conversations();
        let keys: Vec<ConversationKey> = summaries.iter().map(|s| s.key.clone()).collect();
        self.conversation_handles.retain(&keys);
        let rows: Vec<ConversationRow> = summaries
            .iter()
            .map(|summary| {
                let kind = placeholder_en::text(match summary.key {
                    ConversationKey::Direct { .. } => UiText::DirectConversation,
                    ConversationKey::Channel(_) => UiText::ChannelConversation,
                });
                let count = summary.unread.to_string();
                let unread = fill(
                    placeholder_en::text(UiText::UnreadCount),
                    &[("count", &count)],
                );
                ConversationRow {
                    handle: self.conversation_handles.of(&summary.key),
                    title: summary.title.as_str().into(),
                    description: fill(
                        placeholder_en::text(UiText::ConversationDescription),
                        &[("kind", kind), ("unread", &unread)],
                    )
                    .into(),
                    selected: self.shown.as_ref() == Some(&summary.key),
                }
            })
            .collect();
        {
            let mut shared = self.shared.borrow_mut();
            shared.conversations = keys
                .iter()
                .zip(&rows)
                .map(|(key, row)| (row.handle, key.clone()))
                .collect();
        }
        update_by_key(
            &*self.conversations,
            &mut self.conversation_keys,
            &keys,
            &rows,
        );
    }

    fn render_messages(&mut self, model: &UiModel) {
        let items = self
            .shown
            .as_ref()
            .map_or_else(Vec::new, |key| model.messages(key));
        let keys: Vec<ItemKey> = items.iter().map(|i| i.key).collect();
        self.item_handles.retain(&keys);
        let mut rendered = HashMap::new();
        let rows: Vec<MessageRow> = items
            .iter()
            .map(|item| {
                let handle = self.item_handles.of(&item.key);
                let actions: Vec<Intent> = model
                    .actions(item.key)
                    .into_iter()
                    .filter(|i| action_text(i).is_some())
                    .collect();
                let model_rc = match self.action_models.get(&handle) {
                    Some((same, rc)) if *same == actions => rc.clone(),
                    _ => {
                        let rc = action_model(&actions);
                        self.action_models
                            .insert(handle, (actions.clone(), rc.clone()));
                        rc
                    }
                };
                let drawn = self
                    .bodies
                    .entry(item.key)
                    .or_insert_with(|| drawn_body(item));
                let row = message_row(handle, item, model_rc, drawn);
                rendered.insert(
                    handle,
                    Pressable {
                        key: item.key,
                        actions,
                        links: drawn.links.clone(),
                    },
                );
                row
            })
            .collect();
        self.action_models
            .retain(|handle, _| rendered.contains_key(handle));
        self.bodies.retain(|key, _| keys.contains(key));
        self.shared.borrow_mut().items = rendered;
        update_by_key(&*self.messages, &mut self.message_keys, &keys, &rows);
    }

    fn render_chrome(&self, model: &UiModel) {
        let window = &self.window;
        window.set_connectivity(placeholder_en::connectivity(model.connectivity()).into());
        let notice = model.session_notice();
        self.shared.borrow_mut().notice = notice;
        window.set_has_notice(notice.is_some());
        window.set_notice(notice.map(notice_text).unwrap_or_default().into());
        let action = notice
            .and_then(SessionNotice::resolution)
            .and_then(|i| action_text(&i));
        window.set_has_notice_action(action.is_some());
        window.set_notice_action(action.unwrap_or_default().into());

        match &self.shown {
            None => {
                window.set_header_title(placeholder_en::text(UiText::NoConversation).into());
                window.set_header_id(SharedString::new());
                window.set_composer_enabled(false);
                window.set_refused(SharedString::new());
            }
            Some(key) => {
                let title = model
                    .conversations()
                    .into_iter()
                    .find(|s| &s.key == key)
                    .map(|s| s.title)
                    .unwrap_or_default();
                window.set_header_title(title.into());
                window.set_header_id(full_id(key).into());
                window.set_composer_enabled(true);
                let composer = model.composer(key);
                // Never over typing the model has not had yet -- an edit
                // still queued (review F4, rust-ui-dev F2), which, never
                // refused, holds every keystroke -- and only when it
                // differs: writing the same text back would move the
                // person's cursor.
                let pending = self
                    .shared
                    .borrow()
                    .inputs
                    .iter()
                    .any(|i| matches!(i, Input::Draft(k, _) if k == key));
                if !pending && window.get_draft().as_str() != composer.draft {
                    window.set_draft(composer.draft.as_str().into());
                }
                window.set_refused(
                    composer
                        .refused
                        .map(|class| {
                            fill(
                                placeholder_en::text(UiText::NotSent),
                                &[("reason", placeholder_en::error(class))],
                            )
                        })
                        .unwrap_or_default()
                        .into(),
                );
            }
        }
    }
}

/// The four row operations a keyed update makes: a Slint `VecModel`, or
/// in a test a recorder that counts them.
trait Rows<R> {
    fn row(&self, index: usize) -> Option<R>;
    fn set(&self, index: usize, row: R);
    fn insert(&self, index: usize, row: R);
    fn remove(&self, index: usize);
}

impl<R: Clone + 'static> Rows<R> for VecModel<R> {
    fn row(&self, index: usize) -> Option<R> {
        self.row_data(index)
    }
    fn set(&self, index: usize, row: R) {
        self.set_row_data(index, row);
    }
    fn insert(&self, index: usize, row: R) {
        VecModel::insert(self, index, row);
    }
    fn remove(&self, index: usize) {
        VecModel::remove(self, index);
    }
}

/// Bring `model` from the rows keyed `current` to `rows` keyed `keys`,
/// touching only what changed: a row whose data is the same is left
/// alone, and a row that moved is moved alone. Each remove-and-insert
/// rebuilds that row's elements, so when two rows disagree about a
/// position, the one that moved FARTHER moves: a row demoted to the end
/// is one move, not one for every row it passed (review F7).
fn update_by_key<K: PartialEq + Clone, R: Clone + PartialEq>(
    model: &impl Rows<R>,
    current: &mut Vec<K>,
    keys: &[K],
    rows: &[R],
) {
    // Remove what is gone, back to front so indices stay valid.
    for index in (0..current.len()).rev() {
        if !keys.contains(&current[index]) {
            model.remove(index);
            current.remove(index);
        }
    }
    let mut index = 0;
    while index < keys.len() {
        let (key, row) = (&keys[index], &rows[index]);
        match current.iter().position(|k| k == key) {
            Some(at) if at == index => {
                if model.row(index).as_ref() != Some(row) {
                    model.set(index, row.clone());
                }
                index += 1;
            }
            Some(at) => {
                // Everything before `index` is in place, so `at > index`
                // and the row sitting here belongs later.
                let here = keys
                    .iter()
                    .position(|k| *k == current[index])
                    .unwrap_or(index);
                if here - index > at - index {
                    // The row here was demoted farther than `key` was
                    // promoted: take it out; it goes back in at its place.
                    model.remove(index);
                    current.remove(index);
                } else {
                    model.remove(at);
                    current.remove(at);
                    model.insert(index, row.clone());
                    current.insert(index, key.clone());
                    index += 1;
                }
            }
            None => {
                model.insert(index, row.clone());
                current.insert(index, key.clone());
                index += 1;
            }
        }
    }
}

/// The buttons for `actions`, in order: a press is recorded by its index
/// into the actions as rendered.
fn action_model(actions: &[Intent]) -> ModelRc<ActionRow> {
    let rows: Vec<ActionRow> = actions
        .iter()
        .enumerate()
        .filter_map(|(index, intent)| {
            Some(ActionRow {
                index: i32::try_from(index).ok()?,
                text: action_text(intent)?.into(),
            })
        })
        .collect();
    ModelRc::new(VecModel::from(rows))
}

/// An item's body as the view draws it, built once per item.
struct DrawnBody {
    lines: ModelRc<BodyLine>,
    link_rows: ModelRc<LinkRow>,
    /// The destinations, in the order of `link_rows`.
    links: Vec<String>,
    /// The drawn text alone, for the item's label: what a screen reader
    /// reads is the text, not the source's markup.
    plain: String,
}

fn drawn_body(item: &MessageItem) -> DrawnBody {
    let image = |alt: &str| {
        fill(
            placeholder_en::text(UiText::ImageNotLoaded),
            &[("alt", alt)],
        )
    };
    let body = body::flatten(&item.body, &image);
    let plain = body
        .lines
        .iter()
        .map(|line| line.text.as_str())
        .filter(|text| !text.is_empty())
        .collect::<Vec<_>>()
        .join("\n");
    let lines: Vec<BodyLine> = body
        .lines
        .iter()
        .map(|line| {
            let (kind, level) = match line.kind {
                body::Kind::Text => (LineKind::Text, 0),
                body::Kind::Heading(level) => (LineKind::Heading, i32::from(level)),
                body::Kind::Code => (LineKind::Code, 0),
                body::Kind::Rule => (LineKind::Rule, 0),
                body::Kind::TableHeader => (LineKind::TableHeader, 0),
                body::Kind::TableRow => (LineKind::TableRow, 0),
            };
            BodyLine {
                kind,
                level,
                depth: i32::try_from(line.depth).unwrap_or(i32::MAX),
                quoted: line.quoted,
                marker: line.marker.as_str().into(),
                text: line.text.as_str().into(),
            }
        })
        .collect();
    let link_rows: Vec<LinkRow> = body
        .links
        .iter()
        .enumerate()
        .filter_map(|(index, destination)| {
            Some(LinkRow {
                index: i32::try_from(index).ok()?,
                label: fill(
                    placeholder_en::text(UiText::OpenLink),
                    &[("destination", destination)],
                )
                .into(),
            })
        })
        .collect();
    DrawnBody {
        lines: ModelRc::new(VecModel::from(lines)),
        link_rows: ModelRc::new(VecModel::from(link_rows)),
        links: body.links,
        plain,
    }
}

fn message_row(
    handle: i32,
    item: &MessageItem,
    actions: ModelRc<ActionRow>,
    drawn: &DrawnBody,
) -> MessageRow {
    let (author, author_id) = match (&item.direction, &item.author) {
        (Direction::Inbound, Some(peer)) => (short_peer(peer.as_str()), peer.as_str().to_owned()),
        _ => (placeholder_en::text(UiText::You).to_owned(), String::new()),
    };
    let status = status_text(item);
    let route = item
        .route_label
        .as_ref()
        .map(|r| {
            fill(
                placeholder_en::text(UiText::Route),
                &[("route", r.as_str())],
            )
        })
        .unwrap_or_default();
    let reply = match &item.reply {
        Some(Reply::Present(_)) => placeholder_en::text(UiText::ReplyPresent),
        Some(Reply::Unavailable(_)) => placeholder_en::text(UiText::ReplyUnavailable),
        None => "",
    };
    let label = fill(
        placeholder_en::text(UiText::Item),
        &[
            ("author", &author),
            ("status", status),
            ("body", &drawn.plain),
        ],
    );
    MessageRow {
        handle,
        label: label.into(),
        author: author.into(),
        author_id: author_id.into(),
        route: route.into(),
        status: status.into(),
        source: item.source.as_str().into(),
        lines: drawn.lines.clone(),
        links: drawn.link_rows.clone(),
        reply: reply.into(),
        actions,
    }
}

/// The status a person reads: the label's text, and for an unread copy of
/// a kept message, both facts (U2b).
fn status_text(item: &MessageItem) -> &'static str {
    match item.status {
        ItemStatus::Inbound(Retention::Unread) if item.kept => {
            placeholder_en::text(UiText::UnreadAlsoKept)
        }
        _ => placeholder_en::label(item.label),
    }
}

/// The control text for an intent a view offers as a button, or `None`
/// for one it never offers that way: `MarkRead` comes from a focused
/// view alone, `Send` from the composer, `OpenLink` from a link's own
/// control, labelled with its destination.
fn action_text(intent: &Intent) -> Option<&'static str> {
    let text = match intent {
        Intent::Retry(_) => UiText::Retry,
        Intent::Cancel(_) => UiText::Cancel,
        Intent::Keep { .. } => UiText::Keep,
        Intent::Unkeep(_) => UiText::Unkeep,
        Intent::Reopen => UiText::TryAgain,
        Intent::RecheckStorage => UiText::RecheckStorage,
        Intent::MarkRead(_) | Intent::Send { .. } | Intent::OpenLink(_) => return None,
    };
    Some(placeholder_en::text(text))
}

fn notice_text(notice: SessionNotice) -> String {
    match notice {
        SessionNotice::NoDaemon => placeholder_en::text(UiText::NoDaemon).to_owned(),
        SessionNotice::Reconnecting => placeholder_en::text(UiText::Reconnecting).to_owned(),
        SessionNotice::StorageDegraded => placeholder_en::text(UiText::StorageDegraded).to_owned(),
        SessionNotice::Refused(class) => fill(
            placeholder_en::text(UiText::Refused),
            &[("reason", placeholder_en::error(class))],
        ),
    }
}

/// A conversation's full identifier, exact (§11): the `PeerId` of a direct
/// route, the channel id of a channel.
fn full_id(key: &ConversationKey) -> String {
    match key {
        ConversationKey::Direct { peer, .. } => peer.as_str().to_owned(),
        ConversationKey::Channel(channel) => channel.as_str().to_owned(),
    }
}

#[cfg(test)]
mod tests {
    use std::cell::RefCell;

    use super::{Rows, update_by_key};

    /// Rows that count what a keyed update did to them.
    #[derive(Default)]
    struct Recorder {
        rows: RefCell<Vec<char>>,
        moves: RefCell<usize>,
        sets: RefCell<usize>,
    }

    impl Rows<char> for Recorder {
        fn row(&self, index: usize) -> Option<char> {
            self.rows.borrow().get(index).copied()
        }
        fn set(&self, index: usize, row: char) {
            *self.sets.borrow_mut() += 1;
            self.rows.borrow_mut()[index] = row;
        }
        fn insert(&self, index: usize, row: char) {
            *self.moves.borrow_mut() += 1;
            self.rows.borrow_mut().insert(index, row);
        }
        fn remove(&self, index: usize) {
            self.rows.borrow_mut().remove(index);
        }
    }

    /// How many rows were (re)inserted, going from `from` to `to`; the
    /// row's data is its key, so the result is checked as well.
    fn inserts(from: &str, to: &str) -> (usize, usize) {
        let recorder = Recorder::default();
        recorder.rows.borrow_mut().extend(from.chars());
        let mut current: Vec<char> = from.chars().collect();
        let keys: Vec<char> = to.chars().collect();
        update_by_key(&recorder, &mut current, &keys, &keys);
        assert_eq!(*recorder.rows.borrow(), keys, "{from} -> {to}");
        assert_eq!(current, keys);
        (*recorder.moves.borrow(), *recorder.sets.borrow())
    }

    #[test]
    fn a_keyed_update_moves_only_the_row_that_moved() {
        assert_eq!(inserts("abcd", "abcd"), (0, 0), "nothing changed");
        assert_eq!(inserts("abcd", "bcda").0, 1, "a demoted to the end");
        assert_eq!(inserts("abcd", "dabc").0, 1, "d promoted to the front");
        assert_eq!(inserts("abcd", "acd").0, 0, "a removal moves nothing");
        assert_eq!(inserts("abcd", "abxcd").0, 1, "an insertion is one");
        assert_eq!(inserts("abcd", "dcba").0, 3, "a reversal is still correct");
    }
}
